### ISSUE TITLE
Meaningful router to value in snapshot

### ISSUE THREAD

**Issue by adelura** [eddyerburgh/jest-serializer-vue#12]
Hi,

any idea how I could make such output in the snapshot?

``` html
<routerlink-stub to="{ to: "home" }">Home</routerlink-stub>
```

That is the current behaviour.

``` html
<routerlink-stub to="[object Object]">Home</routerlink-stub>
```

**Comment by eddyerburgh** [comment]
There is a feature request for this in Vue Test Utils—https://github.com/vuejs/vue-test-utils/issues/891
