### ISSUE TITLE
Bug in the Readme

### ISSUE THREAD

**Issue by aantipov** [eddyerburgh/jest-serializer-vue#14]
There is an example in the Readme:
```
import { shallow } from '@vue/test-utils'
```

`shallow` should be changed to `shallowMount`, because there is no `shallow` in  `@vue/test-utils`

**Comment by eddyerburgh** [comment]
Thanks for the report, would you like to make a PR with your suggested change?

**Comment by TheJaredWilcurt** [comment]
This can be closed.
