### ISSUE TITLE
Release notes for 2.0.0 are too sparse

### ISSUE THREAD

**Issue by robcresswell** [eddyerburgh/jest-serializer-vue#5]
Hey Edd!

Any chance of the breaking change details for `2.0.0` being a little more detailed? There's nothing in the `CHANGELOG.md` and the Releases page is a bit vague.

**Comment by eddyerburgh** [comment]
I've added an entry to the CHANGELOG and updated the release notes, are they easier to understand?

The update makes it possible to serialize a wrapper instance, so you can pass it straight to the snapshot matcher, and it will be formatted as the HTML generated by the component instance:

```
const wrapper = mount(TestComponent)

expect(wrapper).toMatchSnapshot()
```

**Comment by robcresswell** [comment]
It does help a bit, but I think it would be valuable to explicitly call out that `html()` is no longer needed. A line along of the lines of:

```
serialize Wrapper Instances (#4) 3e8dec0. Create a snapshot with a Vue Test Utils wrapper instance: this means you no longer need to call `.html()` on your wrapper instance before calling `toMatchSnapshot()`.
```

For those of us that are a bit lesser-brained 😝

**Comment by eddyerburgh** [comment]
Thanks for the suggestion, I've updated to include it 😄

**Comment by robcresswell** [comment]
Awesome! I hope that will save some others a little confusion. Thanks for the quick response and work on all the testing 😇
