### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jondavidjohn** [eddyerburgh/jest-serializer-vue#7]
Components that result in no `.html()` result in an error [attempting to call `replace` on `undefined`](https://github.com/eddyerburgh/jest-serializer-vue/blob/master/index.js#L16).

I think the case could be made that `wrapper.html()` should **always** return a string, but that might be outside the scope of handling this inconsistency within the serializer.

I see 2 possible solutions:

1) Check for undefined here in the serializer and return an empty string instead

2) Ensure a string is returned by `wrapper.html()` always.  An empty string in this case.

Would be open to submit a PR for either option.

**Comment by eddyerburgh** [comment]
Hi @jondavidjohn thanks for offering to add a PR.

I think we should handle a null html in this repo 👍
